// Jenkinsfile
pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Bazylgo/jenkins-docker.git'
            }
        }
        stage('Build') {
            steps {
                echo 'Building the application...'
                // Add build steps here, such as `mvn clean install` for Java projects
            }
        }
        stage('Deploy') {
            steps {
                script {
                    def jenkinsUrl = 'http://localhost:8080' // Jenkins server URL
                    // Call or trigger Jenkins-specific steps if needed
                }
            }
        }
    }
}